doc: chapter_02 doc 의미있는 이름
gdsc-ssu/clean_code_master pull request #2
Opened 2022-10-19 09:15 UTC by ChoiSangwon

2장 의미있는 이름 readme.md 정리입니다!
피드백 해주세요~~

2022-10-20 05:05 UTC, yoo-jimin127 approved these changes
내용 정리 너무 깔끔하게 잘 해주신 것 같아요.. 읽어보면서 복습했슴다 !! 👍 
c++로 예제 코드 변경해서 작성해주신 것도 넘 좋아요 !!! 수고하셨습니다 ☺️

2022-10-21 07:39 UTC, kanghyun98 requested changes
고생하셨습니다!👍🏼👍🏼 
몇몇 오타랑 줄바꿈 문제만 해결되면 좋을 것 같습니다!😄

2022-10-21 07:39 UTC, kanghyun98 commented on 02. 의미 있는 이름/README.md
> +### 그릇됫 정보를 피하라
오타입니다!
```suggestion
### 그릇된 정보를 피하라
```

2022-10-21 07:39 UTC, kanghyun98 commented on 02. 의미 있는 이름/README.md
> +  → class라는 이름을 사용했다고 비슷한 발음인 klass사용 (ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ)
저도 이거 보고 웃었는데ㅋㅋㅋㅋㅋㅋ

2022-10-21 07:39 UTC, kanghyun98 commented on 02. 의미 있는 이름/README.md
> +  ex) 계정을 그룹으로 묶을때 accountList라고 명명했을 때 list(배열) 자료형이 아닐 경우 잘못된 정보를 제공하는 것이다. → accountGroup 또는 단순히 Accounts라 명명한다.
소스코드 모드에서는 예제가 밑에 줄에 존재하는데, 왜 렌더링된 뷰에서는 뒤에 이어서 보일까요..?ㅠㅠ
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/70627979/197139595-7b688139-66e2-46c4-a88a-93abaf5c0e63.png">

2022-10-21 07:39 UTC, kanghyun98 commented on 02. 의미 있는 이름/README.md
> +  그래서 클래스를 만든 후 세변수를 클래스에 넣어서 사용하고, 함수를 작은 조강으로 쪼개면 이 함수가 무엇을 하는지 더 분명해진다.
오타입니다!
```suggestion
  그래서 클래스를 만든 후 세변수를 클래스에 넣어서 사용하고, 함수를 작은 조각으로 쪼개면 이 함수가 무엇을 하는지 더 분명해진다.
```

2022-10-21 07:39 UTC, kanghyun98 commented on 02. 의미 있는 이름/README.md
> +</aside>
여기서도 줄바꿈이 제대로 동작하지 않네요,,😭 
<img width="935" alt="image" src="https://user-images.githubusercontent.com/70627979/197140131-2d9b79ef-bc9d-4761-b8b2-555a4aa4e065.png">

2022-10-21 10:24 UTC, ChoiSangwon commented on 02. 의미 있는 이름/README.md
> +  그래서 클래스를 만든 후 세변수를 클래스에 넣어서 사용하고, 함수를 작은 조강으로 쪼개면 이 함수가 무엇을 하는지 더 분명해진다.
아니 무슨 이렇게 오타가 많..... 감사합니다 ㅠㅠ

2022-10-22 11:46 UTC, kanghyun98 approved these changes

2022-10-23 04:47 UTC, Jeoung-Jun-Yeoung approved these changes
넘넘 고생하셨습니다,, 어푸루부우우..

2022-10-23 04:47 UTC, Jeoung-Jun-Yeoung commented on 02. 의미 있는 이름/README.md
> +	💡 우리들 대다수는 자신이 짠 클래스 이름과 메서드 이름을 모두 암기하지 못한다.
너무 공감이 가는 내용이 많은 파트같습니다,, 고생하셨어요!!

2022-10-23 11:09 UTC, pseeej approved these changes
참 잘했어요~^^! 깔끔하게 잘 정리했네요...! 어푸루부드.

2022-10-23 17:38 UTC, White-Patrasche approved these changes

2022-10-23 17:38 UTC, halfmoon-mind commented on 02. 의미 있는 이름/README.md
> +```
c++코드로 되어 있으니까 String이 아니라 string으로 하는게 맞는거 같고 (기존 책에서는 Java로 작성되있어서 Java처럼 작성한거 같은데 정리하면서 작성하신 다른 부분들은 c++으로 작성되어 있어서 통일시켜주면 좋을거 같아요!), 219라인에 '+' 문자 추가되어있어요!

2022-10-24 07:34 UTC, ChoiSangwon commented on 02. 의미 있는 이름/README.md
> +```
넵 감사합니다!

2022-10-24 07:55 UTC, merged