add : Readme.md
gdsc-ssu/clean_code_master pull request #25
Opened 2023-01-15 16:17 UTC by Jeoung-Jun-Yeoung

## Summary

## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] assignees 추가

늦어서 죄송합니다. 열심히 했습니다. 분발하겠습니다. 감사합니다. 좋은하루 보내세요.

2023-01-16 11:19 UTC, pseeej approved these changes
너무나도 어려웠던 주제,,, 정리하시느라 고생 많으셨어요 😭😭

2023-01-16 11:19 UTC, pseeej commented on 11. 시스템/README.md
> +**제작(Construction)**과 **사용(use)**은 아주 다르다.
적용이 안 됐어요,,,

2023-01-16 11:19 UTC, pseeej commented on 11. 시스템/README.md
> +![IMG_E0D4AD0A42A2-1.jpeg](%E1%84%8E%E1%85%A2%E1%86%B8%E1%84%90%E1%85%A511%2057009bbb8bf541debc7622912d9b371f/IMG_E0D4AD0A42A2-1.jpeg)
이미지가 깨져부럿어요

2023-01-16 11:19 UTC, pseeej commented on 11. 시스템/README.md
> +![IMG_5D2D8962F20B-1.jpeg](%E1%84%8E%E1%85%A2%E1%86%B8%E1%84%90%E1%85%A511%2057009bbb8bf541debc7622912d9b371f/IMG_5D2D8962F20B-1.jpeg)
여기도 이미지가 깨져 있어요!

2023-01-16 16:31 UTC, yoo-jimin127 approved these changes
긴 내용 정리하시느라 수고 많으셨습니다!
문서 전반적으로 문장별 줄바꿈과 
메소드명 또는 변수명 등의 경우 `코드처리`데코레이터가 들어가면 
가독성이 더 높아질 것 같습니다..!
일부 수정했는데 확인해주시고 선택 하에 suggestion commit 해주시면 좋을 것 같아요!!
너무너무 고생하셨습니다아~

2023-01-16 16:31 UTC, yoo-jimin127 commented on 11. 시스템/README.md
> +# 시스템 - 케빈 딘 왐플러 박사
header1 크기 제목 하나만 있는게 다른 챕터 doc들과 통일성 있을 것 같습니다!
```suggestion
# 11장 시스템
```

2023-01-16 16:31 UTC, yoo-jimin127 commented on 11. 시스템/README.md
> +흔히 소프트웨어 팀도 도시처럼 구성한다. 그런데 막상 팀이 제작하는 시스템은 비슷한 수준으로 관심사를 분리하거나 추상화를 이뤄내지 못하는데, 깨끗한 코드를 구현하면 낮은 추상화 수준에서 관심사를 분리하기 쉬워진다.
문장 가독성 측면에서 줄바꿈 제안 드립니다!
```suggestion

→ 도시를 한 사람의 힘으로 직접 관리하기란 무리다.   
그럼에도 도시는 일상적으로 잘 돌아가는데 수도 관리팀, 전력 관리팀, 교통 관리 팀 등 각 분야를 관리하는 팀이 있기 때문이다.    
도시는 적절한 추상화와 모듈화로 돌아간다.    
큰 그림을 이해하지 못해도 개인과 개인이 관리하는 ‘구성요소’는 효율적으로 돌아간다.   

흔히 소프트웨어 팀도 도시처럼 구성한다.    
그런데 막상 팀이 제작하는 시스템은 비슷한 수준으로 관심사를 분리하거나 추상화를 이뤄내지 못하는데,    
깨끗한 코드를 구현하면 낮은 추상화 수준에서 관심사를 분리하기 쉬워진다.
```

2023-01-16 16:31 UTC, yoo-jimin127 commented on 11. 시스템/README.md
> +**관심사 분리**는 우리 분야에서 가장 오래되고 가장 중요한 설계 기법중 하나다. 불행히도 대다수 애플리케이션은 시작 단계라는 관심사를 분리하지 않는다. 준비 과정 코드를 주먹구구식으로 구현할 뿐 아니라 런타임 로직과 마구 뒤섞인다.
```suggestion
**관심사 분리**는 우리 분야에서 가장 오래되고 가장 중요한 설계 기법중 하나다.    
불행히도 대다수 애플리케이션은 시작 단계라는 관심사를 분리하지 않는다.    
준비 과정 코드를 주먹구구식으로 구현할 뿐 아니라 런타임 로직과 마구 뒤섞인다.   
```

2023-01-16 16:31 UTC, yoo-jimin127 commented on 11. 시스템/README.md
> +체계적이고 탄탄한 시스템을 만들고 싶다면 흔히 쓰는 좀스럽고 손쉬운 기법으로 모듈성을 깨서는 절대로 안된다. 객체를 생성하거나 의존성을 연결할때도 마찬가지다. 설정 논리는 일반 실행 논리와 분리해야 모듈성이 높아진다. 또한 주요 의존성을 해소하기 위한 방식, 즉 전반적이며 일괄적인 방식도 필요하다.
```suggestion
이것이 초기화 지연 (Lazy initialization) 혹은 계산 지연(Lazy Evaluation)이라는 기법이다.    
장점은 여러가지다.   

1. 실제로 필요할 때까지 객체를 생성하지 않으므로 불필요한 부하가 걸리지 않는다. 따라서 애플리케이션 시작시간이 빨라진다.
2. 어떤 경우에도 null 포인터를 반환하지 않는다.

하지만 `getService` 메서드가 `MyServiceImpl`과 (위에서는 생략한) 생성자 인수에 명시적으로 의존한다.    
런타임 로직에 `MyServiceImpl` 객체를 전혀 사용하지 않더라도 의존성을 해결하지 않으면 컴파일이 안된다.   

테스트도 문제가 된다.    
`MyServiceImpl`이 무거운 객체라면 단위 테스트에서 `getService` 메서드를 호출하기 전에 적절한 테스트 전용 객체를 `service` 필드에 할당해야 한다.   

또한 일반 런타임 로직에다 객체 생성 로직을 섞은 탓에 모든 실행 경로로도 테스트 해야 한다.

즉, 책임이 둘 이라는 말은 메서드가 작업을 두 가지 이상 수행한다는 의미다.    
즉, 작게나마 단일 책임 원칙(Single Responsibility Principle, SRP)을 깬다.   

무엇보다 MyServiceImpl이 모든 상황에서 적합한 객체인지 모른다.    
현실적으로 한 객체 유형이 모든 문맥에 적합할 가능성이 있을까?   

초기화 지연기법을 한 번 정도 사용한다면 별로 심각한 문제가 아니다.    
하지만 많은 애플리케이션이 이처럼 좀스런 설정 기법을 수시로 사용한다.   

체계적이고 탄탄한 시스템을 만들고 싶다면 흔히 쓰는 좀스럽고 손쉬운 기법으로 모듈성을 깨서는 절대로 안된다.    
객체를 생성하거나 의존성을 연결할때도 마찬가지다.    
설정 논리는 일반 실행 논리와 분리해야 모듈성이 높아진다.    
또한 주요 의존성을 해소하기 위한 방식, 즉 전반적이며 일괄적인 방식도 필요하다.   
```

2023-01-16 16:31 UTC, yoo-jimin127 commented on 11. 시스템/README.md
> +	// 목록 11-1
호옥시 여기 목록 11-1 주석 처리 부분에 일부러 tab 처리를 하신 이유가 있을까요???
인덴트 맞춰주시면 더욱 좋을 것 같아요!!

2023-01-18 07:01 UTC, White-Patrasche approved these changes
굉장히 어려운 부분이고, 난해한 주제인데 쉽지 않았네요... 고생하셨어요!!

2023-01-18 07:01 UTC, White-Patrasche commented on 11. 시스템/README.md
> +스프링 관련 자바 코드가거의 필요없으므로 애플리케이션은 사실상 스프링과 독립적이다. 즉, EJB2 시스템이 지녔던 강한 결합이라는 문제가 모두 사라진다.
```suggestion
스프링 관련 자바 코드가 거의 필요없으므로 애플리케이션은 사실상 스프링과 독립적이다. 즉, EJB2 시스템이 지녔던 강한 결합이라는 문제가 모두 사라진다.
```

2023-01-18 11:41 UTC, kanghyun98 requested changes
다른 분들이 매의 눈으로 오타를 거의 다 잡아줘서,, 제가 딱히 리뷰할게 많지 않았네여ㅋㅋ
양이 많고 쉽지 않은 내용이었는데,, 고생 많으셨습니다!

2023-01-18 11:41 UTC, kanghyun98 commented on 11. 시스템/README.md
> +	// 목록 11-1
지민님 제가 문서보고 얘기하려는 것마다 전부 먼저 리뷰 다셨네요ㅋㅋㅋ👍🏼👍🏼

2023-01-18 11:41 UTC, kanghyun98 commented on 11. 시스템/README.md
> +		// 비즈니스 논리..
여기도 코드 주석에 탭이 한번씩 더 들어갔어요!

2023-01-18 11:41 UTC, kanghyun98 commented on 11. 시스템/README.md
> +import java. lang. reflect.*;
두 줄에 모두 띄어쓰기가 잘못 들어가있어요!

2023-01-21 08:26 UTC, kanghyun98 approved these changes

2023-01-21 08:26 UTC, merged