doc : chapter_03 doc 함수 (#3)
gdsc-ssu/clean_code_master pull request #3
Opened 2022-11-07 16:11 UTC by pseeej

3장 함수 정리...라고 하기엔 너무나도 빼곡한 md입니다...!
확인해보시고 수정해야할 부분이 있다면 자유롭게... 알ㄹㅕ주세요!!

2022-11-07 16:32 UTC, White-Patrasche reviewed
워낙 큰 덩어리라 고생하셨어요!
일부 README 부분 수정할만한 곳 추가했습니다!

2022-11-07 16:32 UTC, White-Patrasche commented on 03. 함수/README.md
> +\- **switch문은 작게 만들기 어렵다.
```suggestion
\- **switch문은 작게 만들기 어렵다.**
```
굵게 작성하는 부분에서 **이 안들어가 있어요!

2022-11-07 16:32 UTC, White-Patrasche commented on 03. 함수/README.md
> +  - **OCP(Open Closed Principle)**을 위반한다
```suggestion
  - **SRP(Single Responsibility Principle)** 을 위반한다

  - **OCP(Open Closed Principle)** 을 위반한다
```
저번에도 괄호와 굵게를 함께 사용하면 **로 나오면 버그?가 있어서 해당 부분 추가해주면 좋을거 같아요

2022-11-07 16:32 UTC, halfmoon-mind commented on 03. 함수/README.md
> +\- 많은 경우 **시간적인 결합(temporal coupling)**이나 **순서 종속성(order dependency)을 초래**한다.
```suggestion
\- 많은 경우 **시간적인 결합(temporal coupling) **이나 **순서 종속성(order dependency)을 초래**한다.
```
위와 동일한 굵게 부분

2022-11-07 16:32 UTC, halfmoon-mind commented on 03. 함수/README.md
> +	deletePage(page)
```suggestion
    deletePage(page)
```
아래에는 스페이스바 4번, 이쪽은 탭 1번이에요!

2022-11-07 16:32 UTC, halfmoon-mind commented on 03. 함수/README.md
> +	logging.info(e.getMessage())
```suggestion
    logging.info(e.getMessage())
```
동일합니다

2022-11-07 17:16 UTC, pseeej commented
> 워낙 큰 덩어리라 고생하셨어요!
> 일부 README 부분 수정할만한 곳 추가했습니다!

감사합니다! 댓글 바탕으로 다시 수정했습니다 😃

2022-11-08 00:20 UTC, ChoiSangwon requested changes
내용 자체는 함수 바꾸느라 고생하셨슴돠

2022-11-08 00:20 UTC, ChoiSangwon commented on 03. 함수/README.md
> +  - 2. **인수로 뭔가를 변환해 결과를 반환하는 경우**. InputStream fileopen("MyFile")
-랑 1.중에서 둘중 하나만 써도 될듯합니다
![스크린샷 2022-11-08 오전 9 16 43](https://user-images.githubusercontent.com/21211957/200443032-e1d27d4e-bd5a-4b7d-a5c9-17505244e7de.png)
```suggestion
1. **인수에 질문을 던지는 경우**. boolean fileExists("MyFile")
2. **인수로 뭔가를 변환해 결과를 반환하는 경우**. InputStream fileopen("MyFile")
```

2022-11-08 03:24 UTC, kanghyun98 approved these changes
양이 상당히 많은데 고생 많았슴다!
근데 저번에 정했던 폴더 구조에 따르면 README.md 에는 자바 코드가 들어가긴 하는데,,
일단 이번 PR에서는 그냥 머지하고, 코드 추가하는 PR에서 README.md -> python.md로 변경할까요?

2022-11-08 03:45 UTC, pseeej commented on 03. 함수/README.md
> +  - 2. **인수로 뭔가를 변환해 결과를 반환하는 경우**. InputStream fileopen("MyFile")
수정오나료!

2022-11-08 03:47 UTC, pseeej commented
> 양이 상당히 많은데 고생 많았슴다!
> 근데 저번에 정했던 폴더 구조에 따르면 README.md 에는 자바 코드가 들어가야 하긴 하는데,,
> 일단 이번 PR에서는 그냥 머지하고, 코드 추가하는 PR에서 README.md -> python.md로 변경할까요?

사실 이것도 처음에는 python.md로 했었는데 그 내용 확인받는 과정에서 깔끔하게 보시라고 파일 이름을 README로 했습니다 ㅎ_ㅎ 승인 다 받으면 마지막으로 파일 이름 다시 python으로 변경해서 머지하겠습니다~!

2022-11-08 03:57 UTC, kanghyun98 commented
> > 양이 상당히 많은데 고생 많았슴다!
> 
> > 근데 저번에 정했던 폴더 구조에 따르면 README.md 에는 자바 코드가 들어가야 하긴 하는데,,
> 
> > 일단 이번 PR에서는 그냥 머지하고, 코드 추가하는 PR에서 README.md -> python.md로 변경할까요?
> 
> 
> 
> 사실 이것도 처음에는 python.md로 했었는데 그 내용 확인받는 과정에서 깔끔하게 보시라고 파일 이름을 README로 했습니다 ㅎ_ㅎ 승인 다 받으면 마지막으로 파일 이름 다시 python으로 변경해서 머지하겠습니다~!

오호,,, 센스 무엇,,,👍👍

2022-11-08 04:18 UTC, pseeej commented
ㅎㅎ 아무 버튼이나 눌러보다가 클로즈가 됐네요......... 재오픈!

2022-11-08 07:53 UTC, ChoiSangwon approved these changes

2022-11-08 08:35 UTC, yoo-jimin127 approved these changes
이렇게 예제코드랑 설명 자세하게 작성해주시다니… 함수 챕터 양이 많던데 너무 고생하셨어요 ㅠㅠㅠ👍 문서 완벽하니까 자 이제 예제 코드 쓰러 가겠습니다 ^___^

2022-11-08 08:54 UTC, Jeoung-Jun-Yeoung approved these changes
최고최고! 어려운내용인데 너무너무 고생하셨습니다,, 어푸르부,,,ㅎ.ㅎ

2022-11-09 00:31 UTC, White-Patrasche approved these changes

2022-11-09 13:38 UTC, merged